apiVersion: v1
kind: ConfigMap
metadata:
  name: test
  namespace: opa-operator
  labels:
    opa.stackable.tech/bundle: "true"
data:
  test.rego: |
    package test

    hello {
      true
    }

    world {
      false
    }