apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-rules
  labels:
    opa.stackable.tech/bundle: "true"
data:
{{- range $ruleName, $ruleProperties := .Values.rules }}
  {{ $ruleName }}: |
    {{- $ruleProperties | nindent 4 }}
{{- end }}
