name: Release

on:
  push:
    branches:
      - main

permissions:
  # read needed for changes detection
  # write needed to author a Github release
  contents: write
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:

  changes:
    # Detect which files have been changed on this PR's full history
    uses: SwanseaUniversityMedical/workflows/.github/workflows/changes-release.yaml@v4.1.0
    with:
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      filters: |
        chart:
          - './.github/workflows/on-release.yaml'
          - 'charts/opa/**'

    secrets:
      slack-token: ${{ secrets.SLACK_TOKEN }}

  ######################################################################################################################
  # Chart Tasks
  ######################################################################################################################

  chart:
    # Build the chart and push it as x.y.z-rc
    needs: changes
    if: fromJSON(needs.changes.outputs.changes).chart == 'true'
    uses: SwanseaUniversityMedical/workflows/.github/workflows/on-release-chart.yaml@v4.1.0
    with:
      job-name: chart
      chart-registry: ${{ vars.HARBOR_REGISTRY }}
      chart-registry-user: ${{ vars.HARBOR_USER }}
      chart-registry-project: ${{ vars.HARBOR_PROJECT }}
      chart-registry-repo: ${{ vars.HARBOR_REPO }}
      release-tag-format: 'DARE-OPA-Helm-${version}'
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      chart: charts/opa
      test-command: |
        helm template $CHART --values charts/opa/values.yaml
    secrets:
      chart-registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}
